// The sidebar's three STATIC cards: Show info, Production Region, Holidays.
//
// This is where the "it still looks legacy" was actually coming from. These three cards carried 38
// inline `style=` attributes between them — 166 declarations — hard-coding font-size:13px,
// border:1px solid var(--border-strong), border-radius:7px, padding:6px 8px onto every field. An
// inline style beats every stylesheet rule, so no amount of retokenising the CSS could touch them.
// Replacing the markup is the only thing that removes them.
//
// ⚠️ The OTHER two cards (Phases, All-phase hiatus) are NOT here and cannot be, yet: their contents
// are generated by the engine as HTML strings (buildPhaseRows, phaseHiatusBlockHtml,
// renderEpisodeRows), and those generators also mint the element ids that ARE the save-file format.
// They get Mantine's look through the plain-control rules in legacy.css instead.
//
// ⛔ EVERY CONTROL HERE IS UNCONTROLLED, and that is not a style choice.
// applyStateSnapshot() restores a calendar by writing `el.value` into each field by id. A
// controlled Mantine component ignores that write and re-renders from its own state, so the value
// would silently fail to come back when someone opens a saved calendar — while still saving
// correctly, and while passing every id-based assertion. So: no `value` prop anywhere below, only
// `defaultValue`. See UI-CONVENTIONS.md §2c.
import { useState, useLayoutEffect } from 'react'
import { TextInput, NativeSelect, NumberInput, Button, Text, Group, Stack, Box, Switch, Divider } from '@mantine/core'
import { IconTv, IconMapPin, IconCalendarDot, IconShare, IconSliders, IconHeading } from './icons.jsx'
import { InfoHint } from './InfoHint.jsx'
import { installChrome } from './bridge.js'

const SEASONS = [
  { value: '', label: '—' },
  ...Array.from({ length: 10 }, (_, i) => ({ value: String(i + 1), label: `Season ${i + 1}` })),
]

export function ShowInfoCard() {
  return (
    <section className="card" data-tab="show">
      <h2><IconTv className="card-ic" /><span>Show info</span></h2>
      {/* .side-block: the same bounded white block a phase row gets, so the three React cards and
          the engine-generated Phases card read as ONE system (owner's ask, 29 Aug 2026). */}
      <div className="side-block">
      {/* gap xl, not md (owner, round 5): md is 8px on the density scale and the fields read as
          cramped. 16px of air between fields; the Phases-tab overflow argument in theme.js is
          about input HEIGHT, which this does not touch. */}
      <Stack gap="xl">
        <TextInput id="show-title" label="Title" placeholder="e.g. Show Title" />
        {/* ⛔ NativeSelect, never Select. Select puts the option LABEL in the id-bearing input, so
            this would save "Season 2" where the format expects "2". */}
        <NativeSelect id="season-num" label="Season" data={SEASONS} />
        {/* hideControls: the spinners cost width the sidebar does not have, and every one of these
            is typed rather than stepped. */}
        <NumberInput id="shoot-days-per-ep" label="Shooting Days per Episode" placeholder="e.g. 8"
                     min={1} step={1} allowDecimal={false} allowNegative={false} hideControls />
        <NumberInput id="num-episodes" label="Number of Episodes" placeholder="e.g. 10"
                     min={1} step={1} allowDecimal={false} allowNegative={false} hideControls />
        {/* ⛔ TextInput, never NumberInput (owner decision H1, 1 Sep 2026): owners write 3, 3.1
            and 3a, so the field is a LABEL and not arithmetic. The engine's versionLabel() strips a
            leading v/V, so typing either "3" or "v3" prints "v3".
            ⛔ It is NOT part of showInfoStatus()'s completeness test and must never gate
            Production -- a calendar with no version number is a complete calendar.
            The description answers the one question this field raises that the others do not: where
            does it come out? Nothing else on screen shows it -- the l2 slot is hidden while empty, so
            before you type there is no slot to associate the field with.
            ⚠️ "Shows", not "Prints": the value appears on screen as well as in both exports, and
            "prints" reads as export-only. It is also deliberately weaker than a promise, because it
            is NOT true in Manual mode -- headerLine() returns headerManual[id] there, so a version
            typed onto a manual header changes nothing. Title has behaved that way since the header
            gained modes; the difference is that Title makes no claim. Step 2's mode popover is where
            Auto/Template/Manual gets explained; do not try to fix it with 9px of copy here. */}
        <TextInput id="show-version" label="Version" placeholder="e.g. 3"
                   description={'Shows as “v3” in the header’s bottom-left.'} />
      </Stack>
      {/* Written by showInfoStatus() and shown/hidden by it. */}
      <div className="show-info-note" id="show-info-note" style={{ display: 'none' }}></div>
      </div>
    </section>
  )
}

export function RegionCard() {
  return (
    <section className="card" data-tab="settings">
      <h2>
        <IconMapPin className="card-ic" /><span>Production Region</span>
        {/* Was a permanent three-line paragraph here (owner, 31 Aug 2026). The copy is unchanged;
            only when you see it is. UI-CONVENTIONS.md §4 separated explanation from warning, and
            this takes only the explanation — #union-lock-hint below stays visible. */}
        <InfoHint label="Production Region">
          Sets the union-holiday calendar. Holidays that fall on a Production shoot day are skipped,
          pushing the schedule out. Canada is picked by province and the UK by nation — the statutory lists genuinely differ.
        </InfoHint>
      </h2>
      <div className="side-block">
      {/* Same round-5 spacing as the Show card. */}
      <Stack gap="xl">
        {/* ONE control. The user picks WHERE THEY SHOOT; the agreement resolves behind it and is
            never selected directly -- which is the right way round, because a UPM knows the city
            and should not have to know that Florida is an Area Standards market.
            ⚠️ The option set stays STATIC so a restored save can set any value directly; that is
            the same contract the three old selects had, and the reason none of them were ever
            repopulated per country. */}
        <NativeSelect id="union-place" label="Location">
          <option value="">None</option>
          <optgroup label="United States">
            <option value="us-atlanta">Atlanta, GA</option>
            <option value="us-chicago">Chicago, IL</option>
            <option value="us-florida">Florida — statewide</option>
            <option value="us-los-angeles">Los Angeles, CA</option>
            <option value="us-maryland">Maryland / DC</option>
            <option value="us-miami">Miami, FL</option>
            <option value="us-new-mexico">New Mexico</option>
            <option value="us-new-orleans">New Orleans, LA</option>
            <option value="us-new-york">New York, NY</option>
            <option value="us-oahu">Oahu, HI</option>
            <option value="us-pittsburgh">Pittsburgh, PA</option>
            <option value="us-puerto-rico">Puerto Rico</option>
            <option value="us-san-francisco">San Francisco, CA</option>
            <option value="us-general">Elsewhere in the U.S. — Area Standards</option>
          </optgroup>
          <optgroup label="Canada">
            <option value="ca-montreal">Montreal, QC</option>
            <option value="ca-toronto">Toronto, ON</option>
            <option value="ca-vancouver">Vancouver, BC</option>
            <option value="ca-alberta">Alberta — province-wide</option>
            <option value="ca-bc">British Columbia — province-wide</option>
            <option value="ca-manitoba">Manitoba — province-wide</option>
            <option value="ca-nova-scotia">Nova Scotia — province-wide</option>
            <option value="ca-ontario">Ontario — province-wide</option>
            <option value="ca-quebec">Quebec — province-wide</option>
          </optgroup>
          <optgroup label="United Kingdom">
            <option value="uk-london">London</option>
            <option value="uk-scotland">Scotland</option>
          </optgroup>
          <optgroup label="Australia">
            <option value="au-melbourne">Melbourne, VIC</option>
          </optgroup>
          <optgroup label="Europe">
            <option value="eu-lithuania">Lithuania</option>
          </optgroup>
        </NativeSelect>

        {/* What the city name hides. Written by reflectRegionUI(), so they stay plain elements. */}
        <Box>
          <p id="union-resolves" className="region-resolves"></p>
          <p id="union-locals" className="region-locals"></p>
          {/* Chicago and San Francisco are ASA carve-outs whose agreements are unpublished, so
              their list is a proxy. This is the line a region key had no way to say. */}
          <div id="union-caveat" className="region-caveat" style={{ display: 'none' }}></div>
        </Box>
      </Stack>
      {/* Names three specific controls, so it is a field error rather than an advisory — but it is
          still written by the engine, so it stays a plain element it can fill. */}
      <p id="union-lock-hint" className="lock-hint" style={{ display: 'none' }}>
        Locked — changing the Region would recompute Production’s dates and misplace your
        comment/hiatus edits. Use “Reset Notes &amp; Hiatus” above the calendar first.
      </p>
      </div>
    </section>
  )
}

// ⛔ PREFERENCES, NOT CALENDAR DATA -- and the card says so, because nothing else in this tab
// behaves that way. Production Region and Holidays above it travel INSIDE a saved .sptcal; these
// stay on this computer and never enter captureSnapshot(). Users will not guess that split.
//
// ⛔ `prefs-card` is load-bearing, not decorative: collectFieldValues() sweeps every input[id] /
// select[id] / textarea[id] in the document, and the engine skips this class. Without it the
// control would be baked into every saved calendar AND add a phantom undo step on every change.
// Any future preference control belongs INSIDE this card for that reason alone.
export function PreferencesCard() {
  return (
    <section className="card prefs-card" data-tab="settings">
      <h2>
        <IconSliders className="card-ic" /><span>Preferences</span>
        {/* ⛔ THIS CARD NO LONGER HOLDS ONE KIND OF THING, AND THE HINT HAS TO SAY SO. It used to
            promise "these stay on this computer and are not part of a saved calendar", which was
            true of gridlines and is FALSE of One column -- that one is calendar data, in
            captureSnapshot(), so it travels inside a file you send. Leaving the old wording would
            have been a confident lie about where someone's settings go. */}
        <InfoHint label="Preferences" width={330}>
          Grid lines stay on this computer — send someone a calendar and they keep their own.
          One column belongs to the calendar itself, so it travels with a file you send.
        </InfoHint>
      </h2>
      <div className="side-block">
        {/* Uncontrolled ON PURPOSE: the engine writes .value in reflectGridlines(), the same
            contract #tool-anchor-date has. A controlled input would ignore that write. */}
        {/* ⛔ Export-only, and the description says so: the owner ruled 3 Sep 2026 that this is
            "about the pdf export ... not in the live app view". The editor's own gridlines are
            unchanged by it. */}
        {/* ⛔ No separate "Default" entry (owner, 3 Sep 2026): None IS the default, and a Default
            that merely meant None was a second name for the same output. None is listed first for
            that reason -- it is what a fresh calendar exports and what the reference exports look
            like. */}
        {/* ⚠️ The visible description was removed 9 Sep 2026 at the owner's request ("remove the
            descriptions, theyre not necessary"). Its content -- export-only, the editor's own grid
            is unchanged -- moved into the ⓘ above rather than being deleted: it is the answer to
            "why did nothing change on screen?", and the card title alone does not give it. */}
        {/* Label left, small control right -- the same row shape as Single Column Mode below, so
            the card reads as a list of settings rather than two unrelated widgets (owner, 10 Sep
            2026). The label is a <Text size="sm"> rather than NativeSelect's own `label` prop
            precisely so the two rows share one type scale; the built-in label is a different size.
            ⚠️ "EXPORTS", PLURAL, AND THAT PLURAL IS LOAD-BEARING. This drives SHEET_GRIDLINES, which
            BOTH writers read -- exportExcel draws the workbook's cell borders from it just as
            buildWaterfallPdf draws the PDF's. It briefly shipped as "Grid Lines in PDF Export",
            which was flagged as understating the reach and corrected by the owner the same day.
            ⛔ Uncontrolled, as before: the engine writes .value in reflectGridlines(). */}
        <Group justify="space-between" wrap="nowrap" gap="sm">
          <Text component="label" htmlFor="pref-gridlines" size="sm" style={{ cursor: 'pointer' }}>
            Grid Lines in Exports
          </Text>
          <NativeSelect id="pref-gridlines" size="xs" w={132}
                        aria-label="Grid Lines in Exports">
            <option value="none">None</option>
            <option value="solid">Solid</option>
            <option value="dashed">Dashed (Excel style)</option>
          </NativeSelect>
        </Group>

        {/* Visible separation between settings (owner, 10 Sep 2026) -- two unrelated controls
            stacked with nothing between them read as one confusing group. */}
        <Divider my="sm" />

        {/* ⭐ A real switch, not a button that changes colour (owner: "this should be a toggle like
            in iOS settings"). Mantine's Switch, label left and switch right, which is the settings-row
            shape everyone already knows.
            ⛔ IT IS AN <input type="checkbox"> WITH AN id, INSIDE .prefs-card, AND THAT IS SAFE --
            but only because of the card. collectFieldValues() sweeps `input[id]` into every saved
            calendar and skips this class, so the switch is NOT in fields.byId; One column travels
            instead through captureSnapshot()'s own `singleColumn` key, which is the single source of
            truth. `pref-gridlines` is the same arrangement and predates it.
            ⚠️ AN EARLIER COMMENT HERE CLAIMED A CHECKBOX WOULD BE STORED TWICE AND DISAGREE WITH
            ITSELF. That was wrong, and the correction is worth keeping: skipped-by-the-sweep means
            exactly ONE store, so nothing can disagree. The genuine hazard is the mirror image -- an
            id'd control of any kind placed OUTSIDE this card would be in fields.byId AND the
            snapshot, and those two can drift.
            ⛔ UNCONTROLLED ON PURPOSE: no `checked` prop. The engine owns the state and writes
            .checked in reflectSingleColumn(); a controlled input would fight it on every commit,
            the same contract #pref-gridlines has. */}
        {/* ⚠️ Named by the owner, 10 Sep 2026. The id stays `one-col-btn`: it is the engine's
            binding and both gate legs' handle, and renaming it would buy nothing but breakage. */}
        <Group justify="space-between" wrap="nowrap" gap="sm">
          <Text component="label" htmlFor="one-col-btn" size="sm" style={{ cursor: 'pointer' }}>
            Single Column Mode
          </Text>
          <Switch id="one-col-btn" size="md"
                  aria-label="Single Column Mode"
                  title="Run the whole calendar down one continuous column, from the first working week to the last, instead of a separate block per calendar year" />
        </Group>
      </div>
    </section>
  )
}

// ⛔ SECOND CARD, SAME MARKER CLASS -- and `prefs-card` is the whole reason this split needed care.
// It carries no styling whatsoever (grep legacy.css: there is no `.prefs-card` rule). It exists for
// exactly one job: collectFieldValues() sweeps every input[id] / select[id] / textarea[id] in the
// document and skips this class. Split the card and forget the class on the new half, and every
// control in it is silently baked into every saved calendar with a phantom undo step per keystroke.
// Nothing in here carries an id today, so nothing would break TODAY -- which is precisely why the
// class must be here now, before someone adds the first id'd control and finds out the hard way.
// The hdrpreset leg asserts `.hdr-presets` still resolves `.closest('.prefs-card')`.
export function HeadersCard() {
  return (
    <section className="card prefs-card" data-tab="settings">
      <h2>
        <IconHeading className="card-ic" /><span>Headers</span>
        <InfoHint label="Headers" width={320}>
          The header is the block of text printed above the calendar in the PDF and the workbook.
          Templates and presets stay on this computer; the header you apply travels inside the
          calendar you save.
        </InfoHint>
      </h2>
      <div className="side-block">
        <HeaderPresets />
      </div>
    </section>
  )
}

// The header PRESET library (HEADER-PRESETS-PLAN.md §3.5). Lives in the Preferences card because a
// preset IS a preference -- how this person likes headers, not what this calendar says.
//
// ⛔ NOT ONE `id` ON ANY CONTROL IN HERE, and the .prefs-card skip is not the reason. That skip
// covers controls inside the card; the rule is kept absolutely because it is simpler to hold than to
// audit, and because the one Mantine component that would break it -- `Modal` -- portals to <body>,
// OUTSIDE the card, where the skip does not reach. That is why the Save-as name field is INLINE
// rather than a modal, and why these are plain elements with classes: legacy.css's plain-control
// rules give them the Mantine look, the same way the engine-generated Phases card gets it.
//
// ⛔ THE ENGINE OWNS EVERY ACTION. React renders `data-hdrpreset` attributes and the engine's one
// delegated click handler matches them -- the fileMenu pattern. Nothing here mutates a preset, and
// the component never receives a preset's templates: only names and ids come across the bridge, so a
// re-render cannot become a place where preset content is edited.
function HeaderPresets() {
  const [state, setState] = useState({ items: [], canSave: false, saveHint: '', naming: false, excelBudget: null })
  const [editing, setEditing] = useState(null)   // the id being renamed, or null

  useLayoutEffect(() => {
    installChrome({ headerPresets: (patch) => setState((s) => ({ ...s, ...patch })) })
  }, [])

  const { items, canSave, saveHint, naming, excelBudget } = state
  // Default is always present and always first, so a list of one means "no saved presets yet".
  const userPresets = items.filter((p) => !p.builtin)

  return (
    <div className="hdr-presets">
      {/* ⚠️ The "Header presets" label and its description are gone (owner, 9 Sep 2026). The label
          was also actively WRONG once the editor button landed under it: editing a template is not
          a preset operation, and the description said "the nine header lines" when the format now
          has ten. The card's own title says Headers; the presets get their own sub-label below. */}
      <button type="button" className="hdr-preset-btn is-primary hdr-preset-edit" data-hdrpreset="edit">
        Edit header template…
      </button>

      {/* The Excel budget. Excel rejects a header over 255 characters IN TOTAL, codes included, and
          fails ungracefully -- the workbook writes, then Excel calls it corrupt on open. The export
          trimmer drops trailing lines to stay under, so nothing breaks; the user just loses lines
          without being told. Templates make long headers easy to write, so show the number.
          ⚠️ "about" is not hedging: this is a second copy of a frozen function's arithmetic and can
          drift. exportExcel stays authoritative; the hdrexcel leg is the guard.
          ⚠️ Moved here 9 Sep 2026: it describes THIS calendar's header, and among the preset
          controls it read as a property of the selected preset. */}
      {excelBudget ? (
        <Text size="xxs" c={excelBudget.over ? 'danger.9' : 'dimmed'} className="hdr-presets-budget">
          {excelBudget.over
            ? `Excel header: about ${excelBudget.total} of ${excelBudget.max} characters — too long, so the last lines will be dropped from the workbook.`
            : `Excel header: about ${excelBudget.total} of ${excelBudget.max} characters.`}
        </Text>
      ) : null}

      <Text size="xs" fw={500} className="hdr-presets-label">Presets</Text>

      <Group gap="sm" wrap="nowrap" mt="xs">
        {/* Plain <select>, no id: legacy.css styles it, and nothing can sweep it into a file. */}
        <select className="hdr-preset-select" aria-label="Header preset"
                style={{ flex: '1 1 0', minWidth: 0 }}>
          {items.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}
        </select>
        <button type="button" className="hdr-preset-btn is-primary" data-hdrpreset="apply" style={{ flex: 'none' }}>
          Apply
        </button>
      </Group>

      {naming ? (
        <Group gap="sm" wrap="nowrap" mt="sm">
          <input type="text" className="hdr-preset-name-input" placeholder="Preset name"
                 aria-label="Preset name" autoFocus style={{ flex: '1 1 0', minWidth: 0 }} />
          <button type="button" className="hdr-preset-btn is-primary" data-hdrpreset="save" style={{ flex: 'none' }}>
            Save
          </button>
          <button type="button" className="hdr-preset-btn hdr-preset-btn-quiet" style={{ flex: 'none' }}
                  onClick={() => setState((s) => ({ ...s, naming: false }))}>
            Cancel
          </button>
        </Group>
      ) : (
        <>
          <button type="button" className="hdr-preset-btn is-primary hdr-preset-save-open" disabled={!canSave}
                  onClick={() => setState((s) => ({ ...s, naming: true }))}>
            Save current header as preset…
          </button>
          {/* The reason, not just a dead control. Manual lines are literal values, and saving them
              would pin one calendar's data onto every calendar the preset is applied to (H8). */}
          {!canSave && saveHint ? (
            <Text size="xxs" c="dimmed" className="hdr-presets-hint">{saveHint}</Text>
          ) : null}
        </>
      )}

      {/* Import is always offered: it is how someone gets their FIRST preset, when the list is
          still just Default and there is nothing of their own to export. */}
      <button type="button" className="hdr-preset-btn hdr-preset-import" data-hdrpreset="import">
        Import preset file…
      </button>

      {userPresets.length ? (
        <div className="hdr-preset-list">
          {userPresets.map((p) => (
            <div className="hdr-preset-row" key={p.id}>
              {editing === p.id ? (
                <>
                  <input type="text" className="hdr-preset-rename-input" defaultValue={p.name}
                         aria-label={'Rename ' + p.name} autoFocus
                         style={{ flex: '1 1 0', minWidth: 0 }} />
                  <button type="button" className="hdr-preset-link" data-hdrpreset="rename"
                          data-preset-id={p.id} onClick={() => setEditing(null)}>Save</button>
                  <button type="button" className="hdr-preset-link"
                          onClick={() => setEditing(null)}>Cancel</button>
                </>
              ) : (
                <>
                  <span className="hdr-preset-row-name">{p.name}</span>
                  <button type="button" className="hdr-preset-link"
                          onClick={() => setEditing(p.id)}>Rename</button>
                  <button type="button" className="hdr-preset-link"
                          data-hdrpreset="export" data-preset-id={p.id}>Export…</button>
                  <button type="button" className="hdr-preset-link hdr-preset-link-danger"
                          data-hdrpreset="delete" data-preset-id={p.id}>Delete</button>
                </>
              )}
            </div>
          ))}
        </div>
      ) : null}
    </div>
  )
}

export function AppCard() {
  return (
    <section className="card" data-tab="settings">
      <h2>
        <IconShare className="card-ic" /><span>App</span>
        <InfoHint label="Export App With Data">
          A standalone HTML copy of the app with this calendar loaded — for sending to someone who
          doesn’t have the tool. It opens by double-click, anywhere, offline.
        </InfoHint>
      </h2>
      <div className="side-block">
        {/* #share-copy-btn: the engine's document-delegated click listener matches this id — the
            same flow that used to live on a header button (owner moved it here, 29 Aug 2026). */}
        <Button id="share-copy-btn" type="button" variant="default" size="xs" fullWidth>
          Export App With Data
        </Button>
      </div>
    </section>
  )
}

export function HolidaysCard() {
  return (
    <section className="card" data-tab="settings">
      <h2>
        <IconCalendarDot className="card-ic" /><span>Holidays</span>
        <InfoHint label="Holidays" width={280}>
          Un-tick <strong>Enable</strong> to drop a holiday from this show entirely — it stops costing
          Production a shoot day and stops appearing as a note. The two note columns control where an
          enabled holiday shows up.
        </InfoHint>
      </h2>
      <div className="side-block">
      <Text id="holiday-vis-empty" size="xs" c="dimmed" style={{ display: 'none' }}></Text>

      <div id="holiday-vis" style={{ display: 'none' }}>
        <div className="hv-head">
          <span className="hv-head-name">Holiday</span>
          <span>Enable</span>
          <span>W’fall<br />note</span>
          <span>Month<br />note</span>
        </div>
        {/* Engine-owned: renderHolidayVisList() writes this element's innerHTML, and re-writes it
            on every change — which is why a NodeList captured across a click is detached. */}
        <div id="holiday-vis-list"></div>
        <Group justify="flex-end" gap="lg" mt="sm">
          <Text size="xs" c="dimmed">Toggle all:</Text>
          <button type="button" className="hv-bulk" data-view="enabled">Enable</button>
          <button type="button" className="hv-bulk" data-view="sheet">Waterfall</button>
          <button type="button" className="hv-bulk" data-view="month">Month</button>
        </Group>
      </div>

      </div>

      {/* Custom (show-specific) holidays. A single day, which the hiatus rows cannot express --
          those are whole Monday-snapped weeks. Not region-scoped, so they survive a region change.
          Its own block: it is a different job from the visibility table above it. */}
      <Box className="side-block hv-custom">
        <Text size="xs" fw={500} mb="sm">Add your own holiday</Text>
        {/* ⚠️ The date input no longer has a fixed 132px width and the name field no longer has to
            fight for what is left. Measured before: the row spent 190px on fixed-width children, so
            at the sidebar's 280px floor the name input got 16px, of which 14 was its own padding —
            functionally zero-width on a small laptop. UI-CONVENTIONS.md §5. */}
        <Group gap="sm" align="flex-end" wrap="nowrap">
          <TextInput id="custom-hol-name" placeholder="Studio shutdown" style={{ flex: '1 1 0', minWidth: 0 }} />
          {/* Native date input, not Mantine's DateInput: DateInput is CONTROLLED, and this field is
              cleared imperatively after a successful add. */}
          <input type="date" id="custom-hol-date" aria-label="Holiday date" style={{ flex: '1 1 0', minWidth: 0 }} />
          <Button id="custom-hol-add" type="button" variant="default" size="xs" style={{ flex: 'none' }}>Add</Button>
        </Group>
        <Text id="custom-hol-err" size="xs" c="danger.9" mt="xs" style={{ display: 'none' }}></Text>
      </Box>

      <Group justify="flex-end" mt="lg">
        <Button id="holiday-reset-btn" type="button" variant="subtle" color="gray" size="xs">Reset holidays</Button>
      </Group>
    </section>
  )
}
