// The sidebar's three STATIC cards: Show info, Production Region, Holidays.
//
// This is where the "it still looks legacy" was actually coming from. These three cards carried 38
// inline `style=` attributes between them — 166 declarations — hard-coding font-size:13px,
// border:1px solid var(--border-strong), border-radius:7px, padding:6px 8px onto every field. An
// inline style beats every stylesheet rule, so no amount of retokenising the CSS could touch them.
// Replacing the markup is the only thing that removes them.
//
// ⚠️ The OTHER two cards (Phases, All-phase hiatus) are NOT here and cannot be, yet: their contents
// are generated by the engine as HTML strings (buildPhaseRows, phaseHiatusBlockHtml,
// renderEpisodeRows), and those generators also mint the element ids that ARE the save-file format.
// They get Mantine's look through the plain-control rules in legacy.css instead.
//
// ⛔ EVERY CONTROL HERE IS UNCONTROLLED, and that is not a style choice.
// applyStateSnapshot() restores a calendar by writing `el.value` into each field by id. A
// controlled Mantine component ignores that write and re-renders from its own state, so the value
// would silently fail to come back when someone opens a saved calendar — while still saving
// correctly, and while passing every id-based assertion. So: no `value` prop anywhere below, only
// `defaultValue`. See UI-CONVENTIONS.md §2c.
import { TextInput, NativeSelect, NumberInput, Button, Text, Group, Stack, Box } from '@mantine/core'
import { IconTv, IconMapPin, IconCalendarDot, IconShare, IconSliders } from './icons.jsx'
import { InfoHint } from './InfoHint.jsx'

const SEASONS = [
  { value: '', label: '—' },
  ...Array.from({ length: 10 }, (_, i) => ({ value: String(i + 1), label: `Season ${i + 1}` })),
]

export function ShowInfoCard() {
  return (
    <section className="card" data-tab="show">
      <h2><IconTv className="card-ic" /><span>Show info</span></h2>
      {/* .side-block: the same bounded white block a phase row gets, so the three React cards and
          the engine-generated Phases card read as ONE system (owner's ask, 29 Aug 2026). */}
      <div className="side-block">
      {/* gap xl, not md (owner, round 5): md is 8px on the density scale and the fields read as
          cramped. 16px of air between fields; the Phases-tab overflow argument in theme.js is
          about input HEIGHT, which this does not touch. */}
      <Stack gap="xl">
        <TextInput id="show-title" label="Title" placeholder="e.g. Show Title" />
        {/* ⛔ NativeSelect, never Select. Select puts the option LABEL in the id-bearing input, so
            this would save "Season 2" where the format expects "2". */}
        <NativeSelect id="season-num" label="Season" data={SEASONS} />
        {/* hideControls: the spinners cost width the sidebar does not have, and every one of these
            is typed rather than stepped. */}
        <NumberInput id="shoot-days-per-ep" label="Shooting Days per Episode" placeholder="e.g. 8"
                     min={1} step={1} allowDecimal={false} allowNegative={false} hideControls />
        <NumberInput id="num-episodes" label="Number of Episodes" placeholder="e.g. 10"
                     min={1} step={1} allowDecimal={false} allowNegative={false} hideControls />
      </Stack>
      {/* Written by showInfoStatus() and shown/hidden by it. */}
      <div className="show-info-note" id="show-info-note" style={{ display: 'none' }}></div>
      </div>
    </section>
  )
}

export function RegionCard() {
  return (
    <section className="card" data-tab="settings">
      <h2>
        <IconMapPin className="card-ic" /><span>Production Region</span>
        {/* Was a permanent three-line paragraph here (owner, 31 Aug 2026). The copy is unchanged;
            only when you see it is. UI-CONVENTIONS.md §4 separated explanation from warning, and
            this takes only the explanation — #union-lock-hint below stays visible. */}
        <InfoHint label="Production Region">
          Sets the union-holiday calendar. Holidays that fall on a Production shoot day are skipped,
          pushing the schedule out. Canada is picked by province — the statutory lists genuinely differ.
        </InfoHint>
      </h2>
      <div className="side-block">
      {/* Same round-5 spacing as the Show card. */}
      <Stack gap="xl">
        <NativeSelect id="union-country" label="Country">
          <option value="">None</option>
          <option value="US">United States</option>
          <option value="CA">Canada</option>
          <option value="UK">United Kingdom</option>
          {/* Legacy value from files saved before Canada was split by province. Kept (hidden) so a
              restored file still selects Canada; normalizeRegionSelection() then rewrites it. */}
          <option value="CAN" hidden>Canada</option>
        </NativeSelect>

        {/* US area picker. IATSE's West Coast Studio Local Agreements and the Area Standards
            Agreement carry the SAME 11 holidays, so one "General" list covers LA, Atlanta,
            Albuquerque etc. New York (Local 52) is the genuine exception: it swaps Good Friday for
            Veterans Day. Kept as its own <select> (rather than reusing the province one) so both
            option sets stay static and a restored save can set either value directly.
            ⚠️ display:none is the INITIAL state only — reflectRegionUI() owns it from then on. */}
        <Box id="union-usregion-row" style={{ display: 'none' }}>
          <NativeSelect id="union-usregion" label="Area">
            <option value="US-GEN">General (incl. CA, GA, NM, LA)</option>
            <option value="US-NY">New York (Local 52)</option>
          </NativeSelect>
        </Box>

        {/* Province picker: only meaningful for Canada, whose statutory holidays genuinely differ by
            province (Boxing Day is Ontario-only here; Remembrance Day is BC/AB; Truth and
            Reconciliation is BC/MB; the Fête nationale is Quebec-only). */}
        <Box id="union-subregion-row" style={{ display: 'none' }}>
          <NativeSelect id="union-subregion" label="Province">
            <option value="CA-BC">British Columbia</option>
            <option value="CA-ON">Ontario</option>
            <option value="CA-QC">Quebec</option>
            <option value="CA-AB">Alberta</option>
            <option value="CA-MB">Manitoba</option>
            <option value="CA-NS">Nova Scotia</option>
          </NativeSelect>
        </Box>
      </Stack>
      {/* Names three specific controls, so it is a field error rather than an advisory — but it is
          still written by the engine, so it stays a plain element it can fill. */}
      <p id="union-lock-hint" className="lock-hint" style={{ display: 'none' }}>
        Locked — changing the Region would recompute Production’s dates and misplace your
        comment/hiatus edits. Use “Reset Notes &amp; Hiatus” above the calendar first.
      </p>
      </div>
    </section>
  )
}

// ⛔ PREFERENCES, NOT CALENDAR DATA -- and the card says so, because nothing else in this tab
// behaves that way. Production Region and Holidays above it travel INSIDE a saved .sptcal; these
// stay on this computer and never enter captureSnapshot(). Users will not guess that split.
//
// ⛔ `prefs-card` is load-bearing, not decorative: collectFieldValues() sweeps every input[id] /
// select[id] / textarea[id] in the document, and the engine skips this class. Without it the
// control would be baked into every saved calendar AND add a phantom undo step on every change.
// Any future preference control belongs INSIDE this card for that reason alone.
export function PreferencesCard() {
  return (
    <section className="card prefs-card" data-tab="settings">
      <h2>
        <IconSliders className="card-ic" /><span>Preferences</span>
        <InfoHint label="Preferences" width={300}>
          These stay on this computer and are not part of a saved calendar — send someone a
          calendar and they keep their own settings.
        </InfoHint>
      </h2>
      <div className="side-block">
        {/* Uncontrolled ON PURPOSE: the engine writes .value in reflectGridlines(), the same
            contract #tool-anchor-date has. A controlled input would ignore that write. */}
        {/* ⛔ Export-only, and the description says so: the owner ruled 3 Sep 2026 that this is
            "about the pdf export ... not in the live app view". The editor's own gridlines are
            unchanged by it. */}
        <NativeSelect id="pref-gridlines" label="Grid lines in exports"
                      description="The PDF and Excel. The editor's own grid is unchanged.">
          <option value="">Default</option>
          <option value="solid">Solid</option>
          <option value="dashed">Dashed (Excel style)</option>
          <option value="none">None</option>
        </NativeSelect>
      </div>
    </section>
  )
}

export function AppCard() {
  return (
    <section className="card" data-tab="settings">
      <h2>
        <IconShare className="card-ic" /><span>App</span>
        <InfoHint label="Export App With Data">
          A standalone HTML copy of the app with this calendar loaded — for sending to someone who
          doesn’t have the tool. It opens by double-click, anywhere, offline.
        </InfoHint>
      </h2>
      <div className="side-block">
        {/* #share-copy-btn: the engine's document-delegated click listener matches this id — the
            same flow that used to live on a header button (owner moved it here, 29 Aug 2026). */}
        <Button id="share-copy-btn" type="button" variant="default" size="xs" fullWidth>
          Export App With Data
        </Button>
      </div>
    </section>
  )
}

export function HolidaysCard() {
  return (
    <section className="card" data-tab="settings">
      <h2>
        <IconCalendarDot className="card-ic" /><span>Holidays</span>
        <InfoHint label="Holidays" width={280}>
          Un-tick <strong>Enable</strong> to drop a holiday from this show entirely — it stops costing
          Production a shoot day and stops appearing as a note. The two note columns control where an
          enabled holiday shows up.
        </InfoHint>
      </h2>
      <div className="side-block">
      <Text id="holiday-vis-empty" size="xs" c="dimmed" style={{ display: 'none' }}></Text>

      <div id="holiday-vis" style={{ display: 'none' }}>
        <div className="hv-head">
          <span className="hv-head-name">Holiday</span>
          <span>Enable</span>
          <span>W’fall<br />note</span>
          <span>Month<br />note</span>
        </div>
        {/* Engine-owned: renderHolidayVisList() writes this element's innerHTML, and re-writes it
            on every change — which is why a NodeList captured across a click is detached. */}
        <div id="holiday-vis-list"></div>
        <Group justify="flex-end" gap="lg" mt="sm">
          <Text size="xs" c="dimmed">Toggle all:</Text>
          <button type="button" className="hv-bulk" data-view="enabled">Enable</button>
          <button type="button" className="hv-bulk" data-view="sheet">Waterfall</button>
          <button type="button" className="hv-bulk" data-view="month">Month</button>
        </Group>
      </div>

      </div>

      {/* Custom (show-specific) holidays. A single day, which the hiatus rows cannot express --
          those are whole Monday-snapped weeks. Not region-scoped, so they survive a region change.
          Its own block: it is a different job from the visibility table above it. */}
      <Box className="side-block hv-custom">
        <Text size="xs" fw={500} mb="sm">Add your own holiday</Text>
        {/* ⚠️ The date input no longer has a fixed 132px width and the name field no longer has to
            fight for what is left. Measured before: the row spent 190px on fixed-width children, so
            at the sidebar's 280px floor the name input got 16px, of which 14 was its own padding —
            functionally zero-width on a small laptop. UI-CONVENTIONS.md §5. */}
        <Group gap="sm" align="flex-end" wrap="nowrap">
          <TextInput id="custom-hol-name" placeholder="Studio shutdown" style={{ flex: '1 1 0', minWidth: 0 }} />
          {/* Native date input, not Mantine's DateInput: DateInput is CONTROLLED, and this field is
              cleared imperatively after a successful add. */}
          <input type="date" id="custom-hol-date" aria-label="Holiday date" style={{ flex: '1 1 0', minWidth: 0 }} />
          <Button id="custom-hol-add" type="button" variant="default" size="xs" style={{ flex: 'none' }}>Add</Button>
        </Group>
        <Text id="custom-hol-err" size="xs" c="danger.9" mt="xs" style={{ display: 'none' }}></Text>
      </Box>

      <Group justify="flex-end" mt="lg">
        <Button id="holiday-reset-btn" type="button" variant="subtle" color="gray" size="xs">Reset holidays</Button>
      </Group>
    </section>
  )
}
